<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>  

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.6.1" />
    <PackageReference Include="MonoMod.Backports" Version="1.1.2" />
    <PackageReference Include="MonoMod.ILHelpers" Version="1.1.0" />
  </ItemGroup>

</Project>
